### ISSUE TITLE
No License or Makefile

### ISSUE THREAD

**Issue by bkcsoft** [bboyandru/carpc-controller#1]
Would be nice to know what license this is under.
And also a Makefile (or a line in the readme) for building this :)
(and yes, I see there's an Eclipse project-file, but eclipse is sort-of slow to run on an RPi ;) )

**Comment by E-B41** [comment]
The project is configured for cross-compiling, but you have to edit the paths to match your system.

Since i can't get my toolchain running (problems with linking libs) i made a makefile and now work remotely on the rpi.
Look at the commit requests, there is the code for a working a makefile and i posted mine in the comment section.

**Comment by aistodorescu** [comment]
License file added
